export const colors = {
  primary: '#2563EB',
  primaryLight: '#EFF6FF',
  danger: '#DC2626',
  dangerLight: '#FEF2F2',
  success: '#16A34A',
  successLight: '#F0FDF4',
  warning: '#D97706',
  warningLight: '#FFFBEB',
  text: '#1F2937',
  textLight: '#6B7280',
  border: '#E5E7EB',
  bg: '#F9FAFB',
  white: '#FFFFFF',
  card: '#FFFFFF',
};

export const base = {
  container: {
    maxWidth: 480,
    margin: '0 auto',
    padding: '0 16px',
    direction: 'rtl',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  card: {
    background: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  btn: {
    border: 'none',
    borderRadius: 8,
    padding: '10px 20px',
    cursor: 'pointer',
    fontSize: 15,
    fontWeight: 600,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    transition: 'opacity 0.15s',
  },
  btnPrimary: {
    background: colors.primary,
    color: colors.white,
  },
  btnDanger: {
    background: colors.danger,
    color: colors.white,
  },
  btnSuccess: {
    background: colors.success,
    color: colors.white,
  },
  btnGhost: {
    background: 'transparent',
    color: colors.primary,
    border: `1px solid ${colors.primary}`,
  },
  btnWarning: {
    background: colors.warning,
    color: colors.white,
    border: 'none',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 8,
    border: `1px solid ${colors.border}`,
    fontSize: 15,
    direction: 'rtl',
    boxSizing: 'border-box',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    outline: 'none',
    color: colors.text,
    background: colors.white,
  },
  label: {
    display: 'block',
    marginBottom: 4,
    fontWeight: 600,
    color: colors.text,
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  errorBox: {
    background: colors.dangerLight,
    color: colors.danger,
    border: `1px solid ${colors.danger}`,
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    marginBottom: 12,
    direction: 'rtl',
  },
  successBox: {
    background: colors.successLight,
    color: colors.success,
    border: `1px solid ${colors.success}`,
    borderRadius: 8,
    padding: '10px 14px',
    fontSize: 14,
    marginBottom: 12,
    direction: 'rtl',
  },
};
